#!/usr/bin/env bash

## WIP need to re-format and figure out how I want to sort weekly notes (week of?)

this_week=$(date -dmonday +"%Y-%m-%d")
next_week=$(date -dnext-monday +"%Y-%m-%d")
last_week=$(-dlast-monday +"%Y-%m-%d")
file="$SECOND_BRAIN/periodic-notes/weekly-notes/$this_week.md"

cd "$SECOND_BRAIN" || exit

new_note() {
  touch "$file"

  cat <<EOF >"$file"
# week $monday of 

[[$last_week]] - [[$next_week]]

# Intentions (these are the things that I intend to do this week)
[[intentions]]

# Goals (these should surpass the week but can be evaluated weekly)
[[goals]]

# Outcomes (these will be links to where I achieved what I said I would)
- [[]]
- [[]]
- [[]]

## Log
EOF

}

if [ ! -f "$file" ]; then
  echo "File does not exist, creating new daily note."
  new_note
fi

nvim "$file"
