#!/usr/bin/env bash

today=$(date +"%Y-%m-%d")
file="$SECOND_BRAIN"'/workouts/workout-'"$today".md

cd "$SECOND_BRAIN" || exit

new_workout() {
	touch "$file"

	cat <<EOF >"$file"
# Workout

# $today

# Options

1. 3 sets of 6 kettle bell excercises [ ]
2. 30 minute minimum run [ ]

# Daily

1. Stretching [ ]

EOF
}

if [ ! -f "$file" ]; then
	echo "File does not exist, creating new workout."
	new_workout
fi

nvim "$file"
